##### GLOBAL DEFINITIONS AND SUBSTITUTIONS #####
globals:
  - id: boot_done
    type: bool
    initial_value: "false"
  - id: wifi_ok
    type: bool
    initial_value: "false"
  - id: api_ok
    type: bool
    initial_value: "false"
  - id: system_status_led_brightness
    type: float
    restore_value: yes
    initial_value: "-1"
  - id: system_status_led_effect_length
    type: int
    initial_value: "1000"  # default length for effects in ms

substitutions:
  # Default values for the package. Can be overridden in the main configuration file.
  system_status_led_id: "system_status_led"   # Default
  system_status_led_brightness: "50%"         # used for first start + may be used for legacy effects
  length_fast_pulse: "400"                    # no unit allowed, value in ms
  length_slow_pulse: "1000"                   # no unit allowed, value in ms
  length_breath: "2500"                       # no unit allowed, value in ms
  blink_on_off_time: "200ms"                  # unit required

external_components:
  - source: 
      type: git
      url: https://github.com/Flo-R1der/ESPHome_RGB-Status-LED_Package
      ref: test_external-component
    components: [system_status_led_fx]
    refresh: 1d

# Input Number to set the brightness of the LED from Home Assistant.
number:
  - platform: template
    id: system_status_led_brightness_number
    name: "Brightness System Status LED"
    icon: "mdi:label-percent-outline"
    min_value: 0
    max_value: 100
    step: 1
    unit_of_measurement: "%"
    entity_category: "config"
    mode: "slider"
    optimistic: true
    set_action:
      - lambda: 'id(system_status_led_brightness) = (x / 100.0);'
      - script.execute: led_system_status


##### CATCH SYSTEM EVENTS #####
# boot priority values: https://esphome.io/components/esphome/#configuration-variables-1
esphome:
  on_boot:
    - priority: 700
      then:
        - script.execute: led_system_status
    - priority: -10
      then:
        - delay: 500ms
          # depending on your board, the red LED may light up so shortly that you don't see it
          # this delay ensures the red light comes up and you can recognize boot-loop issues
        - if:
            condition: 
              - lambda: "return id(system_status_led_brightness) == -1;"
            then:
              - lambda: |-
                  id(system_status_led_brightness) = ( ${system_status_led_brightness[:-1]} / 100 );
        - number.set:
            id: system_status_led_brightness_number
            value: !lambda "return id(system_status_led_brightness) * 100;"
        - lambda: 'id(boot_done) = true;'
        - script.execute: led_system_status

wifi:
  on_connect:
    then:
      - lambda: 'id(wifi_ok) = true;'
      - script.execute: led_system_status
  on_disconnect:
    then:
      - lambda: 'id(wifi_ok) = false;'
      - script.execute: led_system_status

api:
  on_client_connected:
    then:
      - lambda: 'id(api_ok) = true;'
      - script.execute: led_system_status
  on_client_disconnected:
    then:
      - lambda: 'id(api_ok) = false;'
      - script.execute: led_system_status


##### ASSIGN COLORS TO LED #####
script:
  - id: led_system_status
    mode: restart
    then:
      # API CONNECTED (Priority 4) - green (steady)
      - if:
          condition:
            lambda: 'return id(api_ok);'
          then:
            - light.turn_on:
                id: ${system_status_led_id}
                red: 0%
                green: 100%
                blue: 10%
                brightness: !lambda 'return id(system_status_led_brightness);'
                effect: none
            - script.stop:
                id: led_system_status

      # WIFI OK (Priority 3) - white (steady)
      - if:
          condition:
            lambda: 'return id(wifi_ok);'
          then:
            - light.turn_on:
                id: ${system_status_led_id}
                red: 70%
                green: 70%
                blue: 70%
                brightness: !lambda 'return id(system_status_led_brightness);'
                effect: none
            - script.stop:
                id: led_system_status

      # BOOT DONE (Priority 2) - yellow (steady)
      - if:
          condition:
            lambda: 'return id(boot_done);'
          then:
            - light.turn_on:
                id: ${system_status_led_id}
                red: 80%
                green: 80%
                blue: 0
                brightness: !lambda 'return id(system_status_led_brightness);'
                effect: none
            - script.stop:
                id: led_system_status

      # BOOTING (Priority 1) - red (steady)
      - light.turn_on:
          id: ${system_status_led_id}
          red: 100%
          green: 0
          blue: 0
          brightness: !lambda 'return id(system_status_led_brightness);'
          effect: none



##### ADDITIONAL WORKING MODES #####
# will not end automatically / can be overridden by system status script.
  - id: led_working_status_blue
    parameters:
      effect: string 
    then:
      - script.execute:
          id: system_status_led_effect_handler
          red: 0
          green: 0
          blue: 1
          effect: !lambda 'return effect;'
  - id: led_working_status_1  # LEGACY ALIAS → led_working_status_blue
    then:
      - script.execute: 
          id: led_working_status_blue
          effect: "Slow Pulse"

  - id: led_working_status_purple
    parameters:
      effect: string
    then:
      - script.execute:
          id: system_status_led_effect_handler
          red: 0.8
          green: 0
          blue: 0.8
          effect: !lambda 'return effect;'
  - id: led_working_status_2  # LEGACY ALIAS → led_working_status_purple
    then:
      - script.execute:
          id: led_working_status_purple
          effect: "Slow Pulse"

  - id: led_working_status_red
    parameters:
      effect: string
    then:
      - script.execute:
          id: system_status_led_effect_handler
          red: 1
          green: 0
          blue: 0
          effect: !lambda 'return effect;'

  - id: led_working_status_orange
    parameters:
      effect: string
    then:
      - script.execute:
          id: system_status_led_effect_handler
          red: 1
          green: 0.5
          blue: 0
          effect: !lambda 'return effect;'

  - id: led_working_status_yellow
    parameters:
      effect: string
    then:
      - script.execute:
          id: system_status_led_effect_handler
          red: 0.8
          green: 0.8
          blue: 0
          effect: !lambda 'return effect;'

  - id: led_working_status_green
    parameters:
      effect: string
    then:
      - script.execute:
          id: system_status_led_effect_handler
          red: 0
          green: 1
          blue: 0
          effect: !lambda 'return effect;'

  - id: led_working_status_cyan
    parameters:
      effect: string
    then:
      - script.execute:
          id: system_status_led_effect_handler
          red: 0
          green: 1
          blue: 1
          effect: !lambda 'return effect;'

  - id: led_working_status_white
    parameters:
      effect: string
    then:
      - script.execute:
          id: system_status_led_effect_handler
          red: 0.7
          green: 0.7
          blue: 0.7
          effect: !lambda 'return effect;'


##### SHORT FEEDBACK MODES #####
# will end automatically and return to the LED system status.
  - id: led_feedback_blink_blue
    parameters:
      count: int
    then:
      - repeat:
          count: !lambda 'return count;'
          then:
            - light.turn_on:
                id: ${system_status_led_id}
                red: 0%
                green: 0%
                blue: 100%
                brightness: !lambda 'return id(system_status_led_brightness);'
            - delay: ${blink_on_off_time}
            - light.turn_off: ${system_status_led_id}
            - delay: ${blink_on_off_time}

  - id: led_feedback_blink_purple
    parameters:
      count: int
    then:
      - repeat:
          count: !lambda 'return count;'
          then:
            - light.turn_on:
                id: ${system_status_led_id}
                red: 80%
                green: 0%
                blue: 80%
                brightness: !lambda 'return id(system_status_led_brightness);'
            - delay: ${blink_on_off_time}
            - light.turn_off: ${system_status_led_id}
            - delay: ${blink_on_off_time}

  - id: led_feedback_blink_red
    parameters:
      count: int
    then:
      - repeat:
          count: !lambda 'return count;'
          then:
            - light.turn_on:
                id: ${system_status_led_id}
                red: 100%
                green: 0%
                blue: 0%
                brightness: !lambda 'return id(system_status_led_brightness);'
            - delay: ${blink_on_off_time}
            - light.turn_off: ${system_status_led_id}
            - delay: ${blink_on_off_time}

  - id: led_feedback_blink_orange
    parameters:
      count: int
    then:
      - repeat:
          count: !lambda 'return count;'
          then:
            - light.turn_on:
                id: ${system_status_led_id}
                red: 100%
                green: 50%
                blue: 0%
                brightness: !lambda 'return id(system_status_led_brightness);'
            - delay: ${blink_on_off_time}
            - light.turn_off: ${system_status_led_id}
            - delay: ${blink_on_off_time}

  - id: led_feedback_blink_yellow
    parameters:
      count: int
    then:
      - repeat:
          count: !lambda 'return count;'
          then:
            - light.turn_on:
                id: ${system_status_led_id}
                red: 80%
                green: 80%
                blue: 0%
                brightness: !lambda 'return id(system_status_led_brightness);'
            - delay: ${blink_on_off_time}
            - light.turn_off: ${system_status_led_id}
            - delay: ${blink_on_off_time}

  - id: led_feedback_blink_green
    parameters: 
      count: int
    then:
      - repeat:
          count: !lambda 'return count;'
          then:
            - light.turn_on:
                id: ${system_status_led_id}
                red: 0%
                green: 100%
                blue: 0%
                brightness: !lambda 'return id(system_status_led_brightness);'
            - delay: ${blink_on_off_time}
            - light.turn_off: ${system_status_led_id}
            - delay: ${blink_on_off_time}

  - id: led_feedback_blink_cyan
    parameters:
      count: int
    then:
      - repeat:
          count: !lambda 'return count;'
          then:
            - light.turn_on:
                id: ${system_status_led_id}
                red: 0%
                green: 100%
                blue: 100%
                brightness: !lambda 'return id(system_status_led_brightness);'
            - delay: ${blink_on_off_time}
            - light.turn_off: ${system_status_led_id}
            - delay: ${blink_on_off_time}

  - id: led_feedback_blink_white
    parameters:
      count: int
    then:
      - repeat:
          count: !lambda 'return count;'
          then:
            - light.turn_on:
                id: ${system_status_led_id}
                red: 70%
                green: 70%
                blue: 70%
                brightness: !lambda 'return id(system_status_led_brightness);'
            - delay: ${blink_on_off_time}
            - light.turn_off: ${system_status_led_id}
            - delay: ${blink_on_off_time}


##### LED EFFECT HANDLER #####
# This script is called by the working status scripts to set the desired effect
# with the correct lengt and brightness.
  - id: system_status_led_effect_handler
    parameters:
      effect: string
      red: float
      green: float
      blue: float
    then:
      - globals.set:
          id: system_status_led_effect_length
          value: !lambda |-
            if (effect == "none") {
              return 0;
            } else if (effect == "Fast Pulse") {
              return ${length_fast_pulse};
            } else if (effect == "Slow Pulse") {
              return ${length_slow_pulse};
            } else if (effect == "Breath") {
              return ${length_breath};
            } else {
              return 1000;
            }
      - logger.log:
          format: "Setting LED effect to \"%s\" with length: %dms (%.0f%% brightness)"
          args: ['effect.c_str()', 'id(system_status_led_effect_length)', 'id(system_status_led_brightness)']
          level: INFO
      - light.turn_on:
          id: system_status_led
          red: !lambda 'return red;'
          green: !lambda 'return green;'
          blue: !lambda 'return blue;'
          effect: "Pulse"
          brightness: !lambda 'return id(system_status_led_brightness);'
      - delay: 100ms
      # - lambda: |-
      #     std::string effectName = id(system_status_led).get_effect_name();
      #     ESP_LOGI("system_status_led", "Current detected effect name: %s", effectName.c_str());
      - if:
          condition:
            lambda: |-
              return id(system_status_led).get_effect_name() != "Pulse";
          then:
            - lambda: |-
                ESP_LOGW("system_status_led", "New flexible effect seems to be missing? Trying to use the legacy effects.");
                ESP_LOGW("system_status_led", "Please update your Status-LED settings in your project!");
                ESP_LOGW("system_status_led", "Details here: https://github.com/Flo-R1der/ESPHome_RGB-Status-LED_Package");
            - light.turn_on:
                id: system_status_led
                red: !lambda 'return red;'
                green: !lambda 'return green;'
                blue: !lambda 'return blue;'
                effect: !lambda 'return effect;'
                brightness: !lambda 'return id(system_status_led_brightness);'
